nome = input('Insira seu nome completo\n>>')
nome_upper = nome.upper()
print(nome_upper)
nome_low = nome.lower()
print(nome_low)
nome_len = nome.replace(" ", "")
print(len(nome_len))
primeiro_nome = nome.split()
print(primeiro_nome[0])